### ISSUE TITLE
Re:Zero OP2

### ISSUE THREAD

**Issue by Abrediel** [AngyNoT/AnimeSpotify#1]
**Anime** : Re:Zero
**Song type** : Opening 2
**Season** : Spring 2016
**Title** : Paradisus-Paradoxum 
**Singer** :  MYTH & ROID
**Spotify link** : https://open.spotify.com/album/1G6AOMc4A9Ky2M6Vx05ERO

**Comment by aniplaylist** [comment]
Thanks! I'm adding the first ending too.
