### ISSUE TITLE
Sound of Destiny (Live at Campus Festival)

### ISSUE THREAD

**Issue by wrought13** [AngyNoT/AnimeSpotify#14]
**Anime** : White Album 2
**Song type** : Insert
**Season** : Fall 2013
**Title** : Sound of Destiny (Live at Campus Festival)
**Singer** : Madoka Yonezawa (Setsuna Ogiso)
**Spotify link** : https://open.spotify.com/track/7Ioy6vekqZGOkQTToeZGGX

**Comment by aniplaylist** [comment]
Hello! 

Can you tell me on which episode of White Album 2 this song was? 

Thank you

**Comment by wrought13** [comment]
looks like episode 7 at 9:04
