### ISSUE TITLE
Namida no Mukou

### ISSUE THREAD

**Issue by wrought13** [AngyNoT/AnimeSpotify#2]
**Anime** : Mobile Suit Gundam 00 season 2
**Song type** : Opening 2
**Season** : Fall 2008
**Title** : Namida no Mukou
**Singer** : Stereopony
**Spotify link** : https://open.spotify.com/track/4UqCpvmOL8FiohnarAoRRx

**Comment by aniplaylist** [comment]
The song is now in the playlists, thank you!
