### ISSUE TITLE
MHA OP1 is now on Spotify

### ISSUE THREAD

**Issue by danrozenberg** [AngyNoT/AnimeSpotify#48]
**Anime** : My Hero Academy
**Song type** : Opening 1
**Season** : Spring 2016
**Title** : The Day
**Singer** :  Porno Graffitti
**Spotify link** : https://open.spotify.com/track/1tjOClAkdMxDfYPO0xvGbG

**Comment by aniplaylist** [comment]
Hello @danrozenberg

This song is already in our playlists but don't hesitate to send us other suggestions (here or on Twitter [@AniPlaylist](https://twitter.com/AniPlaylist)) !

Thank you
